go2rtc:
  streams:
    reolink_doorbell:   # <------ Name the stream (match to camera name below in camera section)
      - "ffmpeg:http://[DOORBELL IP ADDRESS]/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=[DOORBELL WEB UI USERNAME]&password=[DOORBELL WEB UI PASSWORD]#video=copy#audio=copy#audio=opus"
      - rtsp://[DOORBELL IP ADDRESS]/Preview_01_sub
    reolink_doorbell_sub:   # <------ Name the stream (match to camera name below in camera section)
      - "ffmpeg:http://[DOORBELL IP ADDRESS]/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=[DOORBELL WEB UI USERNAME]&password=[DOORBELL WEB UI PASSWORD]"

cameras:
  amcrest_1: # <------ Name the camera
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://[CAMERA WEB UI USERNAME]:[CAMERA WEB UI PASSWORD]@[CAMERA IP ADDRESS]/cam/realmonitor?channel=1&subtype=0  # <----- The stream you want to use for detection (this subpath works for this Amcrest Camera model)
          roles:
            - record
        - path: rtsp://[CAMERA WEB UI USERNAME]:[CAMERA WEB UI PASSWORD]@[CAMERA IP ADDRESS]/cam/realmonitor?channel=1&subtype=1  # <----- The sub stream, typically supporting low resolutions only (this subpath works for this Amcrest Camera model)
          roles:
            - detect
    detect:
      enabled: True
      width: 1280  # <---- update for your camera's resolution, on the detect stream (substream)
      height: 720  # <---- update for your camera's resolution, on the detect stream (substream)
      fps: 20      # <---- update for your camera's FPS

  reolink_doorbell:   # <------ Match to go2rtc stream camera name above
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/reolink_doorbell   # <------ Match to go2rtc stream camera name above
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/reolink_doorbell_sub   # <------ Match to go2rtc substream camera name above
          input_args: preset-rtsp-restream
          roles:
            - detect

detectors:
  coral_1:    # <------ Name the device
    type: edgetpu
    device: pci:0

objects:
  track:
    - person
    - eye glasses
    - cell phone
    - laptop

review:
  alerts:
    labels:
      - person
  detections:
    labels:
      - car
      - dog
      - bird

mqtt:
  enabled: false

ffmpeg:
  hwaccel_args: preset-vaapi  # <----- For integrating Intel iGPU after passthrough (might need to be changed to preset-intel-qsv-h264 or preset-intel-qsv-h265 as of version 0.15)
  # output_args:              # <----- Optional, audio inclusion
  #   record: preset-record-generic-audio-aac

snapshots:
  enabled: false
  # timestamp: true
  # bounding_box: true
  # retain:
    # default: 30

record:
  enabled: false      # <----- If recording is disabled in the config, turning it on via the UI or MQTT later will have no effect. 
  # retain:
  #   days: 0
  #   mode: all
  # alerts:
    # retain:
      # days: 30
      # mode: active_objects
    # pre_capture: 5      # <----- Number of seconds before the detection to include (default)
    # post_capture: 10    # <----- Number of seconds after the detection to include (default)
  # detections:
    # retain:
      # days: 30          # <----- Number of days to retain recordings
      # mode: active_objects     # <------ Mode for retention (all | motion | active_objects)
    # pre_capture: 5
    # post_capture: 10
version: 0.15
